In [1]:
import pandas as pd
from config import username, password
import sqlalchemy as sa

In [2]:
#connected to base
engine = sa.create_engine(f'postgresql://({username}):{password}@localhost:5438/postgres')

In [3]:
#read farmers_markets csv 8804 rows × 59 columns
farmer_market = pd.read_csv('resources/farmers_markets_from_usda.csv')
farmer_market.head()

,FMID,MarketName,Website,Facebook,Twitter,Youtube,OtherMedia,street,city,County,...,Coffee,Beans,Fruits,Grains,Juices,Mushrooms,PetFood,Tofu,WildHarvested,updateTime
0,1018261,Caledonia Farmers Market Association - Danville,https://sites.google.com/site/caledoniafarmers...,https://www.facebook.com/Danville.VT.Farmers.M...,NaN,NaN,NaN,NaN,Danville,Caledonia,...,Y,Y,Y,N,N,Y,Y,N,N,6/20/2017 22:43
1,1018318,Stearns Homestead Farmers' Market,http://www.StearnsHomestead.com,StearnsHomesteadFarmersMarket,NaN,NaN,NaN,6975 Ridge Road,Parma,Cuyahoga,...,N,N,Y,N,N,N,N,N,N,6/21/2017 17:15
2,1009364,106 S. Main Street Farmers Market,http://thetownofsixmile.wordpress.com/,NaN,NaN,NaN,NaN,106 S. Main Street,Six Mile,Pickens,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
3,1010691,10th Steet Community Farmers Market,NaN,NaN,NaN,NaN,http://agrimissouri.com/mo-grown/grodetail.php...,10th Street and Poplar,Lamar,Barton,...,N,N,Y,N,N,N,N,N,N,10/28/2014 9:49
4,1002454,112st Madison Avenue,NaN,NaN,NaN,NaN,NaN,112th Madison Avenue,New York,New York,...,N,N,N,N,N,N,N,N,N,3/1/2012 10:38

In [4]:
#read svi_county .csv 3143 rows × 158 columns
svi_county = pd.read_csv('resources/SVI2020_US_COUNTY.csv')
svi_county

,ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,...,EP_ASIAN,MP_ASIAN,EP_AIAN,MP_AIAN,EP_NHPI,MP_NHPI,EP_TWOMORE,MP_TWOMORE,EP_OTHERRACE,MP_OTHERRACE
0,1,Alabama,AL,1001,Autauga,1001,"Autauga County, Alabama",594.455838,55639,0,...,1.2,0.3,0.3,0.2,0.0,0.1,2.0,0.7,0.2,0.3
1,1,Alabama,AL,1003,Baldwin,1003,"Baldwin County, Alabama",1589.835294,218289,0,...,0.9,0.2,0.6,0.2,0.0,0.1,1.9,0.4,0.3,0.2
2,1,Alabama,AL,1005,Barbour,1005,"Barbour County, Alabama",885.007618,25026,0,...,0.5,0.1,0.3,0.3,0.0,0.1,1.3,0.6,0.6,0.4
3,1,Alabama,AL,1007,Bibb,1007,"Bibb County, Alabama",622.469288,22374,0,...,0.3,0.4,0.1,0.1,0.0,0.2,0.4,0.3,0.0,0.2
4,1,Alabama,AL,1009,Blount,1009,"Blount County, Alabama",644.890375,57755,0,...,0.4,0.1,0.1,0.1,0.1,0.1,1.8,0.3,0.3,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56,Wyoming,WY,56037,Sweetwater,56037,"Sweetwater County, Wyoming",10426.975770,43352,0,...,0.7,0.3,1.0,0.4,0.0,0.1,2.2,0.8,0.2,0.3
3139,56,Wyoming,WY,56039,Teton,56039,"Teton County, Wyoming",3996.846846,23356,0,...,1.4,0.8,0.2,0.2,0.1,0.1,1.0,0.6,0.6,0.8
3140,56,Wyoming,WY,56041,Uinta,56041,"Uinta County, Wyoming",2081.719808,20374,0,...,0.2,0.2,0.5,0.3,0.0,0.2,2.2,0.4,0.0,0.2
3141,56,Wyoming,WY,56043,Washakie,56043,"Washakie County, Wyoming",2238.678265,7933,0,...,0.0,0.4,0.4,0.4,0.0,0.4,3.2,0.5,0.4,0.4
3142,56,Wyoming,WY,56045,Weston,56045,"Weston County, Wyoming",2398.003892,6942,0,...,1.6,1.6,0.6,1.0,1.7,2.0,2.9,1.9,0.0,0.5

In [5]:
#created svicounty_df  with selected column fields 3143 rows × 14 columns
svicounty_df = svi_county[['STATE','COUNTY','E_TOTPOP','E_POV150','M_POV150','E_UNEMP','M_UNEMP','E_HBURD','M_HBURD','E_NOHSDP','M_NOHSDP','E_UNINSUR','M_UNINSUR','E_MINRTY','M_MINRTY','EP_MINRTY','MP_MINRTY','EPL_MINRTY']]
svicounty_df.head()

,STATE,COUNTY,E_TOTPOP,E_POV150,M_POV150,E_UNEMP,M_UNEMP,E_HBURD,M_HBURD,E_NOHSDP,M_NOHSDP,E_UNINSUR,M_UNINSUR,E_MINRTY,M_MINRTY,EP_MINRTY,MP_MINRTY,EPL_MINRTY
0,Alabama,Autauga,55639,12611,1349,736,185,5029,576,4273,562,4345,725,14479,578,26.0,1.0,0.6337
1,Alabama,Baldwin,218289,36413,2802,4027,714,19350,1526,14823,1344,20501,1932,37334,1866,17.1,0.9,0.5022
2,Alabama,Barbour,25026,8965,673,649,182,2305,298,4497,387,2362,311,13694,271,54.7,1.1,0.8962
3,Alabama,Bibb,22374,5730,907,667,260,1580,319,3056,414,1878,387,5724,156,25.6,0.7,0.6292
4,Alabama,Blount,57755,13624,1151,1253,301,4060,431,6838,499,5746,695,7690,344,13.3,0.6,0.4147

In [6]:
#created farmer_market_df  with selected column fields 8804 rows × 10 columns
farmer_market_df = farmer_market[['FMID','MarketName','street','city','County','State','zip','x','y']]
farmer_market_df.head()

,FMID,MarketName,street,city,County,State,zip,x,y
0,1018261,Caledonia Farmers Market Association - Danville,NaN,Danville,Caledonia,Vermont,5828,-72.140335,44.411037
1,1018318,Stearns Homestead Farmers' Market,6975 Ridge Road,Parma,Cuyahoga,Ohio,NaN,-81.733940,41.374802
2,1009364,106 S. Main Street Farmers Market,106 S. Main Street,Six Mile,Pickens,South Carolina,29682,-82.818703,34.804199
3,1010691,10th Steet Community Farmers Market,10th Street and Poplar,Lamar,Barton,Missouri,64759,-94.274620,37.495628
4,1002454,112st Madison Avenue,112th Madison Avenue,New York,New York,New York,10029,-73.949303,40.793900

In [7]:
#remove any null values
clean_farm_market=farmer_market_df[farmer_market_df['County'].notna()]
clean_farm_market

,FMID,MarketName,street,city,County,State,zip,x,y
0,1018261,Caledonia Farmers Market Association - Danville,NaN,Danville,Caledonia,Vermont,5828,-72.140335,44.411037
1,1018318,Stearns Homestead Farmers' Market,6975 Ridge Road,Parma,Cuyahoga,Ohio,NaN,-81.733940,41.374802
2,1009364,106 S. Main Street Farmers Market,106 S. Main Street,Six Mile,Pickens,South Carolina,29682,-82.818703,34.804199
3,1010691,10th Steet Community Farmers Market,10th Street and Poplar,Lamar,Barton,Missouri,64759,-94.274620,37.495628
4,1002454,112st Madison Avenue,112th Madison Avenue,New York,New York,New York,10029,-73.949303,40.793900
...,...,...,...,...,...,...,...,...,...
8799,1004767,Zia Bernalillo Farmers' Market,335 S. Camino del Pueblo,Bernalillo,Sandoval,New Mexico,NaN,-106.546840,35.313705
8800,1018362,Zimmerman Farmers' Market,25850 Main Street,Zimmerman,Sherburne,Minnesota,NaN,-93.583809,45.438774
8801,1012380,Zion Canyon Farmers Market,1212 Zion Park Blvd.,Springdale,Washington,Utah,84767,-113.004940,37.181499
8802,1004686,Zionsville Farmers Market,Hawthorne & Main Street,Zionsville,Boone,Indiana,46077,-86.261200,39.949100
8803,1011418,Zona Rosa Farmers' Market,Off of I-29 and Barry Road,Kansas City,Platte,Missouri,64153,-94.580864,39.246319

In [8]:
#remove any null values
clean_svicounty_df=svicounty_df[svicounty_df['COUNTY'].notna()]
clean_svicounty_df

,STATE,COUNTY,E_TOTPOP,E_POV150,M_POV150,E_UNEMP,M_UNEMP,E_HBURD,M_HBURD,E_NOHSDP,M_NOHSDP,E_UNINSUR,M_UNINSUR,E_MINRTY,M_MINRTY,EP_MINRTY,MP_MINRTY,EPL_MINRTY
0,Alabama,Autauga,55639,12611,1349,736,185,5029,576,4273,562,4345,725,14479,578,26.0,1.0,0.6337
1,Alabama,Baldwin,218289,36413,2802,4027,714,19350,1526,14823,1344,20501,1932,37334,1866,17.1,0.9,0.5022
2,Alabama,Barbour,25026,8965,673,649,182,2305,298,4497,387,2362,311,13694,271,54.7,1.1,0.8962
3,Alabama,Bibb,22374,5730,907,667,260,1580,319,3056,414,1878,387,5724,156,25.6,0.7,0.6292
4,Alabama,Blount,57755,13624,1151,1253,301,4060,431,6838,499,5746,695,7690,344,13.3,0.6,0.4147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,Wyoming,Sweetwater,43352,7713,1048,1437,348,2718,406,2098,396,5079,712,9205,604,21.2,1.4,0.5672
3139,Wyoming,Teton,23356,2779,765,280,173,2057,415,945,399,2666,692,4387,324,18.8,1.4,0.5331
3140,Wyoming,Uinta,20374,3673,688,453,200,995,240,903,191,2273,518,2581,145,12.7,0.7,0.4007
3141,Wyoming,Washakie,7933,1484,348,170,76,577,156,441,134,950,243,1446,64,18.2,0.8,0.5210
3142,Wyoming,Weston,6942,1316,356,118,77,522,147,329,116,781,257,649,246,9.3,3.5,0.3001

In [9]:
clean_farm_market.loc[(clean_farm_market['County'] == 'Deklab') & (clean_farm_market['State'] == 'Alabama'), 'County'] = 'Dekalb'
clean_farm_market.loc[(clean_farm_market['County'] == 'Valdex Cordova') & (clean_farm_market['State'] == 'Alaska'), 'County'] = 'Chugach'
clean_farm_market.loc[(clean_farm_market['County'] == 'Valdez-Cordova') & (clean_farm_market['State'] == 'Alaska'), 'County'] = 'Chugach'
clean_farm_market.loc[(clean_farm_market['County'] == 'Juneau') & (clean_farm_market['State'] == 'Alaska'), 'County'] = 'Juneau City and Borough'
clean_farm_market.loc[(clean_farm_market['County'] == 'Wrangell-Petersburg') & (clean_farm_market['State'] == 'Alaska'), 'County'] = 'Petersburg'
clean_farm_market.loc[(clean_farm_market['County'] == 'Sitka') & (clean_farm_market['State'] == 'Alaska'), 'County'] = 'Sitka City and Borough'
clean_farm_market.loc[(clean_farm_market['County'] == 'Shasta') & (clean_farm_market['State'] == 'Arkansas'), 'County'] = 'Benton'
clean_farm_market.loc[(clean_farm_market['County'] == 'St. Anislaus') & (clean_farm_market['State'] == 'California'), 'County'] = 'Stanislaus'
clean_farm_market.loc[(clean_farm_market['County'] == 'Coweta ') & (clean_farm_market['State'] == 'Georgia'), 'County'] = 'Coweta'
clean_farm_market.loc[(clean_farm_market['County'] == 'Dade') & (clean_farm_market['State'] == 'Florida'), 'County'] = 'Miami-Dade'
clean_farm_market.loc[(clean_farm_market['County'] == 'Anderson') & (clean_farm_market['State'] == 'Indiana'), 'County'] = 'Madison'
clean_farm_market.loc[(clean_farm_market['County'] == 'La Porte') & (clean_farm_market['State'] == 'Indiana'), 'County'] = 'LaPorte'
clean_farm_market.loc[(clean_farm_market['County'] == 'Placer') & (clean_farm_market['State'] == 'Indiana'), 'County'] = 'Dekalb'
clean_farm_market.loc[(clean_farm_market['County'] == 'La Salle') & ((clean_farm_market['State'] == 'Louisiana') | (clean_farm_market['State'] == 'Illinois')), 'County'] = 'LaSalle'
clean_farm_market.loc[(clean_farm_market['County'] == 'Anderoscoggin') & (clean_farm_market['State'] == 'Maine'), 'County'] = 'Androscoggin'
clean_farm_market.loc[(clean_farm_market['County'] == 'Burlington ') & (clean_farm_market['State'] == 'New Jersey'), 'County'] = 'Burlington'
clean_farm_market.loc[(clean_farm_market['County'] == 'Dona Ana') & (clean_farm_market['State'] == 'New Mexico'), 'County'] = 'Doña Ana'
clean_farm_market.loc[(clean_farm_market['County'] == 'Miama ') & (clean_farm_market['State'] == 'Ohio'), 'County'] = 'Miami'
clean_farm_market.loc[(clean_farm_market['County'] == 'Northhampton') & (clean_farm_market['State'] == 'Pennsylvania'), 'County'] = 'Northampton'
clean_farm_market.loc[(clean_farm_market['County'] == 'Shannon') & (clean_farm_market['State'] == 'South Dakota'), 'County'] = 'Oglala Lakota'
clean_farm_market.loc[(clean_farm_market['County'] == 'Carrollton') & (clean_farm_market['State'] == 'Texas'), 'County'] = 'Dallas'
clean_farm_market.loc[(clean_farm_market['County'] == 'EL Paso') & (clean_farm_market['State'] == 'Texas'), 'County'] = 'El Paso'
clean_farm_market.loc[(clean_farm_market['County'] == 'Harris ') & (clean_farm_market['State'] == 'Texas'), 'County'] = 'Harris'

clean_farm_market.loc[(clean_farm_market['County'] == 'Chesapeake') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Chesapeake City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Chesapeake City') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Chesapeake City'

clean_farm_market.loc[(clean_farm_market['County'] == 'Chesterfield County') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Chesterfield'
clean_farm_market.loc[(clean_farm_market['County'] == 'Galax City') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Galax City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Galax') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Galax City'

clean_farm_market.loc[(clean_farm_market['County'] == 'Hampton') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Hampton City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Falls Church') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Falls Church city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Charlottesville') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Charlottesville city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Norfolk') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Norfolk city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Lynchburg') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Lynchburg city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Norton') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Norton city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Virginia Beach') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Virginia Beach city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Portsmouth') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Portsmouth city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Radford') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Radford city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Petersburg') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Petersburg city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Monroe') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Albemarle County'
clean_farm_market.loc[(clean_farm_market['County'] == 'Suffolk') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Suffolk city'
clean_farm_market.loc[(clean_farm_market['County'] == 'Chesterfield') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Chesterfield'
clean_farm_market.loc[(clean_farm_market['County'] == 'Alexandria') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Alexandria City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Manassas') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Manassas City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Williamsburg') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Williamsburg City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Buena Vista') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Buena Vista City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Newport News') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Newport News City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Colonial Heights') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Colonial Heights City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Emporia') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Emporia City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Albemarle County') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Albemarle County'

clean_farm_market.loc[(clean_farm_market['County'] == 'Danville') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Danville City'
clean_farm_market.loc[(clean_farm_market['County'] == 'Albemarle County') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Albemarle County'

clean_farm_market.loc[(clean_farm_market['County'] == 'Chesterfied') & (clean_farm_market['State'] == 'Virginia'), 'County'] = 'Chesterfield'
clean_farm_market.loc[(clean_farm_market['County'] == 'Goshen ') & (clean_farm_market['State'] == 'Wyoming'), 'County'] = 'Goshen'
clean_farm_market.loc[(clean_farm_market['County'] == 'Thurston ') & (clean_farm_market['State'] == 'Wyoming'), 'County'] = 'Thurston'

In [10]:
# transform county names to lowercase for merging
clean_svicounty_df['county_lower']=clean_svicounty_df['COUNTY'].str.lower()
clean_farm_market['county_lower']=clean_farm_market['County'].str.lower()

/var/folders/m_/4vd7r1_j4ns82qlq3w4g2c8m0000gp/T/ipykernel_54860/1522928147.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_farm_market['county_lower']=clean_farm_market['County'].str.lower()

In [11]:
#created clean_svicounty_dff and created merge
clean_svicounty_dff = pd.merge(clean_farm_market, clean_svicounty_df, how="outer", right_on=['county_lower','STATE'], left_on=['county_lower','State'])
clean_svicounty_dff

,FMID,MarketName,street,city,County,State,zip,x,y,county_lower,...,M_HBURD,E_NOHSDP,M_NOHSDP,E_UNINSUR,M_UNINSUR,E_MINRTY,M_MINRTY,EP_MINRTY,MP_MINRTY,EPL_MINRTY
0,1018261.0,Caledonia Farmers Market Association - Danville,NaN,Danville,Caledonia,Vermont,5828,-72.140335,44.411037,caledonia,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
1,1018262.0,Caledonia Farmers Market Association - Saturday,Pearl St,St. Johnsbury,Caledonia,Vermont,5819,-72.016640,44.416901,caledonia,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
2,1018263.0,Caledonia Farmers Market Association - Winter,Depot Square,St. Johnsbury,Caledonia,Vermont,5819,-72.015396,44.417210,caledonia,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
3,1008831.0,Groton Growers Farmers' Market,1476 Scott Highway,Groton,Caledonia,Vermont,NaN,-72.197395,44.211525,caledonia,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
4,1006630.0,Hardwick Farmers' Market,Granite St.,Hardwick,Caledonia,Vermont,5843,-72.371513,44.506611,caledonia,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,menominee,...,77.0,216.0,70.0,1156.0,255.0,4130.0,3570.0,90.5,78.2,0.9946
9641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,oconto,...,258.0,2409.0,231.0,1505.0,160.0,2076.0,418.0,5.5,1.1,0.1181
9642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pepin,...,86.0,484.0,69.0,583.0,151.0,278.0,40.0,3.8,0.6,0.0344
9643,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,waushara,...,158.0,2146.0,187.0,1763.0,251.0,2633.0,153.0,10.9,0.6,0.3523
9644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,crook,...,105.0,357.0,146.0,615.0,205.0,448.0,121.0,6.0,1.6,0.1515

In [12]:
# rename columns
clean_svicounty_dff = clean_svicounty_dff.rename(columns={
    'street':'street_farm',
    'city':'city_farm',
    'County':'county_farm',
    'State':'state_farm',
    'zip':'zip_farm',
    'x':'x_farm',
    'y':'y_farm',
    'COUNTY':'county_svi',
    'STATE':'state_svi'
})

# for error checking - delete before final push ###################################### delete me
farm_nan_df = clean_svicounty_dff.loc[(clean_svicounty_dff['county_svi'].isnull())]
farm_nan_df = farm_nan_df[['county_farm','state_farm','county_svi','state_svi','county_lower']]
farm_nan_df = farm_nan_df[farm_nan_df.state_farm != 'Puerto Rico']
farm_nan_df.sort_values('state_farm')

           county_farm state_farm county_svi state_svi      county_lower
8570  Talladega County    Alabama        NaN       NaN  talladega county
2230       Pima County    Arizona        NaN       NaN       pima county
2231       Pima County    Arizona        NaN       NaN       pima county
2232       Pima County    Arizona        NaN       NaN       pima county
7241  Sebastian County   Arkansas        NaN       NaN  sebastian county
...                ...        ...        ...       ...               ...
8575    Jackson County  Wisconsin        NaN       NaN    jackson county
8200  Winnebago County  Wisconsin        NaN       NaN  winnebago county
6432      Pepin County  Wisconsin        NaN       NaN      pepin county
6433      Pepin County  Wisconsin        NaN       NaN      pepin county
7700      Vilas County  Wisconsin        NaN       NaN      vilas county

[126 rows x 5 columns]

In [13]:
final_svicounty_dff = clean_svicounty_dff.drop(columns=['county_lower'])
final_svicounty_dff = final_svicounty_dff[final_svicounty_dff.state_farm != 'Puerto Rico'] ## add this line to this cell since svi data are not available for PR
final_svicounty_dff.head()

,FMID,MarketName,street_farm,city_farm,county_farm,state_farm,zip_farm,x_farm,y_farm,state_svi,...,M_HBURD,E_NOHSDP,M_NOHSDP,E_UNINSUR,M_UNINSUR,E_MINRTY,M_MINRTY,EP_MINRTY,MP_MINRTY,EPL_MINRTY
0,1018261.0,Caledonia Farmers Market Association - Danville,NaN,Danville,Caledonia,Vermont,5828,-72.140335,44.411037,Vermont,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
1,1018262.0,Caledonia Farmers Market Association - Saturday,Pearl St,St. Johnsbury,Caledonia,Vermont,5819,-72.016640,44.416901,Vermont,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
2,1018263.0,Caledonia Farmers Market Association - Winter,Depot Square,St. Johnsbury,Caledonia,Vermont,5819,-72.015396,44.417210,Vermont,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
3,1008831.0,Groton Growers Farmers' Market,1476 Scott Highway,Groton,Caledonia,Vermont,NaN,-72.197395,44.211525,Vermont,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445
4,1006630.0,Hardwick Farmers' Market,Granite St.,Hardwick,Caledonia,Vermont,5843,-72.371513,44.506611,Vermont,...,326.0,1548.0,216.0,1270.0,258.0,1759.0,189.0,5.9,0.6,0.1445

In [14]:
final_svicounty_dff.to_csv('resources/farmers_market_svi.csv')