In [1]:
import pandas as pd
from config import username, password
import sqlalchemy as sa

In [2]:
#connected to base
engine = sa.create_engine(f'postgresql://({username}):{password}@localhost:5438/postgres')

In [4]:
#read farmers_markets csv 8804 rows × 59 columns
farmer_market = pd.read_csv('resources/farmers_markets_from_usda.csv')
farmer_market.head()

,FMID,MarketName,Website,Facebook,Twitter,Youtube,OtherMedia,street,city,County,...,Coffee,Beans,Fruits,Grains,Juices,Mushrooms,PetFood,Tofu,WildHarvested,updateTime
0,1018261,Caledonia Farmers Market Association - Danville,https://sites.google.com/site/caledoniafarmers...,https://www.facebook.com/Danville.VT.Farmers.M...,NaN,NaN,NaN,NaN,Danville,Caledonia,...,Y,Y,Y,N,N,Y,Y,N,N,6/20/2017 22:43
1,1018318,Stearns Homestead Farmers' Market,http://www.StearnsHomestead.com,StearnsHomesteadFarmersMarket,NaN,NaN,NaN,6975 Ridge Road,Parma,Cuyahoga,...,N,N,Y,N,N,N,N,N,N,6/21/2017 17:15
2,1009364,106 S. Main Street Farmers Market,http://thetownofsixmile.wordpress.com/,NaN,NaN,NaN,NaN,106 S. Main Street,Six Mile,Pickens,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013
3,1010691,10th Steet Community Farmers Market,NaN,NaN,NaN,NaN,http://agrimissouri.com/mo-grown/grodetail.php...,10th Street and Poplar,Lamar,Barton,...,N,N,Y,N,N,N,N,N,N,10/28/2014 9:49
4,1002454,112st Madison Avenue,NaN,NaN,NaN,NaN,NaN,112th Madison Avenue,New York,New York,...,N,N,N,N,N,N,N,N,N,3/1/2012 10:38

In [18]:
#read svi_county .csv 3143 rows × 158 columns
svi_county = pd.read_csv('resources/SVI2020_US_COUNTY.csv')
svi_county

,ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,...,EP_ASIAN,MP_ASIAN,EP_AIAN,MP_AIAN,EP_NHPI,MP_NHPI,EP_TWOMORE,MP_TWOMORE,EP_OTHERRACE,MP_OTHERRACE
0,1,Alabama,AL,1001,Autauga,1001,"Autauga County, Alabama",594.455838,55639,0,...,1.2,0.3,0.3,0.2,0.0,0.1,2.0,0.7,0.2,0.3
1,1,Alabama,AL,1003,Baldwin,1003,"Baldwin County, Alabama",1589.835294,218289,0,...,0.9,0.2,0.6,0.2,0.0,0.1,1.9,0.4,0.3,0.2
2,1,Alabama,AL,1005,Barbour,1005,"Barbour County, Alabama",885.007618,25026,0,...,0.5,0.1,0.3,0.3,0.0,0.1,1.3,0.6,0.6,0.4
3,1,Alabama,AL,1007,Bibb,1007,"Bibb County, Alabama",622.469288,22374,0,...,0.3,0.4,0.1,0.1,0.0,0.2,0.4,0.3,0.0,0.2
4,1,Alabama,AL,1009,Blount,1009,"Blount County, Alabama",644.890375,57755,0,...,0.4,0.1,0.1,0.1,0.1,0.1,1.8,0.3,0.3,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,56,Wyoming,WY,56037,Sweetwater,56037,"Sweetwater County, Wyoming",10426.975770,43352,0,...,0.7,0.3,1.0,0.4,0.0,0.1,2.2,0.8,0.2,0.3
3139,56,Wyoming,WY,56039,Teton,56039,"Teton County, Wyoming",3996.846846,23356,0,...,1.4,0.8,0.2,0.2,0.1,0.1,1.0,0.6,0.6,0.8
3140,56,Wyoming,WY,56041,Uinta,56041,"Uinta County, Wyoming",2081.719808,20374,0,...,0.2,0.2,0.5,0.3,0.0,0.2,2.2,0.4,0.0,0.2
3141,56,Wyoming,WY,56043,Washakie,56043,"Washakie County, Wyoming",2238.678265,7933,0,...,0.0,0.4,0.4,0.4,0.0,0.4,3.2,0.5,0.4,0.4
3142,56,Wyoming,WY,56045,Weston,56045,"Weston County, Wyoming",2398.003892,6942,0,...,1.6,1.6,0.6,1.0,1.7,2.0,2.9,1.9,0.0,0.5

In [17]:
# svi_county.set_index('FIPS',drop=True, inplace=True)
# svi_county

,ST,STATE,ST_ABBR,STCNTY,COUNTY,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,E_HU,...,EP_ASIAN,MP_ASIAN,EP_AIAN,MP_AIAN,EP_NHPI,MP_NHPI,EP_TWOMORE,MP_TWOMORE,EP_OTHERRACE,MP_OTHERRACE
FIPS,,,,,,,,,,,,,,,,,,,,,
1001,1,Alabama,AL,1001,Autauga,"Autauga County, Alabama",594.455838,55639,0,23697,...,1.2,0.3,0.3,0.2,0.0,0.1,2.0,0.7,0.2,0.3
1003,1,Alabama,AL,1003,Baldwin,"Baldwin County, Alabama",1589.835294,218289,0,116747,...,0.9,0.2,0.6,0.2,0.0,0.1,1.9,0.4,0.3,0.2
1005,1,Alabama,AL,1005,Barbour,"Barbour County, Alabama",885.007618,25026,0,12057,...,0.5,0.1,0.3,0.3,0.0,0.1,1.3,0.6,0.6,0.4
1007,1,Alabama,AL,1007,Bibb,"Bibb County, Alabama",622.469288,22374,0,9237,...,0.3,0.4,0.1,0.1,0.0,0.2,0.4,0.3,0.0,0.2
1009,1,Alabama,AL,1009,Blount,"Blount County, Alabama",644.890375,57755,0,24404,...,0.4,0.1,0.1,0.1,0.1,0.1,1.8,0.3,0.3,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,56,Wyoming,WY,56037,Sweetwater,"Sweetwater County, Wyoming",10426.975770,43352,0,19842,...,0.7,0.3,1.0,0.4,0.0,0.1,2.2,0.8,0.2,0.3
56039,56,Wyoming,WY,56039,Teton,"Teton County, Wyoming",3996.846846,23356,0,14015,...,1.4,0.8,0.2,0.2,0.1,0.1,1.0,0.6,0.6,0.8
56041,56,Wyoming,WY,56041,Uinta,"Uinta County, Wyoming",2081.719808,20374,0,9077,...,0.2,0.2,0.5,0.3,0.0,0.2,2.2,0.4,0.0,0.2
56043,56,Wyoming,WY,56043,Washakie,"Washakie County, Wyoming",2238.678265,7933,0,3861,...,0.0,0.4,0.4,0.4,0.0,0.4,3.2,0.5,0.4,0.4
56045,56,Wyoming,WY,56045,Weston,"Weston County, Wyoming",2398.003892,6942,0,3571,...,1.6,1.6,0.6,1.0,1.7,2.0,2.9,1.9,0.0,0.5

In [19]:
#created svicounty_df  with selected column fields 3143 rows × 14 columns
svicounty_df = svi_county[['STATE','COUNTY','E_TOTPOP','E_POV150','M_POV150','E_UNEMP','M_UNEMP','E_HBURD','M_HBURD','E_NOHSDP','M_NOHSDP','E_UNINSUR','M_UNINSUR','E_MINRTY','M_MINRTY','EP_MINRTY','MP_MINRTY','EPL_MINRTY']]
svicounty_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATE       3143 non-null   object
 1   COUNTY      3143 non-null   object
 2   E_TOTPOP    3143 non-null   int64
 3   E_POV150    3143 non-null   int64
 4   M_POV150    3143 non-null   int64
 5   E_UNEMP     3143 non-null   int64
 6   M_UNEMP     3143 non-null   int64
 7   E_HBURD     3143 non-null   int64
 8   M_HBURD     3143 non-null   int64
 9   E_NOHSDP    3143 non-null   int64
 10  M_NOHSDP    3143 non-null   int64
 11  E_UNINSUR   3143 non-null   int64
 12  M_UNINSUR   3143 non-null   int64
 13  E_MINRTY    3143 non-null   int64
 14  M_MINRTY    3143 non-null   int64
 15  EP_MINRTY   3143 non-null   float64
 16  MP_MINRTY   3143 non-null   float64
 17  EPL_MINRTY  3143 non-null   float64
dtypes: float64(3), int64(13), object(2)
memory usage: 442.1+ KB

In [20]:
#created farmer_market_df  with selected column fields 8804 rows × 10 columns
farmer_market_df = farmer_market[['FMID','MarketName','street','city','County','State','zip','x','y']]
farmer_market_df.head()

,FMID,MarketName,street,city,County,State,zip,x,y
0,1018261,Caledonia Farmers Market Association - Danville,NaN,Danville,Caledonia,Vermont,5828,-72.140335,44.411037
1,1018318,Stearns Homestead Farmers' Market,6975 Ridge Road,Parma,Cuyahoga,Ohio,NaN,-81.733940,41.374802
2,1009364,106 S. Main Street Farmers Market,106 S. Main Street,Six Mile,Pickens,South Carolina,29682,-82.818703,34.804199
3,1010691,10th Steet Community Farmers Market,10th Street and Poplar,Lamar,Barton,Missouri,64759,-94.274620,37.495628
4,1002454,112st Madison Avenue,112th Madison Avenue,New York,New York,New York,10029,-73.949303,40.793900

In [27]:
#remove any null values
clean_farm_market=farmer_market_df.dropna()
clean_farm_market

,FMID,MarketName,street,city,County,State,zip,x,y
2,1009364,106 S. Main Street Farmers Market,106 S. Main Street,Six Mile,Pickens,South Carolina,29682,-82.818703,34.804199
3,1010691,10th Steet Community Farmers Market,10th Street and Poplar,Lamar,Barton,Missouri,64759,-94.274620,37.495628
4,1002454,112st Madison Avenue,112th Madison Avenue,New York,New York,New York,10029,-73.949303,40.793900
5,1011100,12 South Farmers Market,3000 Granny White Pike,Nashville,Davidson,Tennessee,37204,-86.790710,36.118370
6,1009845,125th Street Fresh Connect Farmers' Market,"163 West 125th Street and Adam Clayton Powell,...",New York,New York,New York,10027,-73.948250,40.808952
...,...,...,...,...,...,...,...,...,...
8797,1019792,Zelienople-Harmony Farmer's Market,Beaver Street and South Division Street,Zelienople,Butler,Pennsylvania,16063,-80.130180,40.792698
8798,1007097,Zerns Farmers Market and Auction,1100 E. Philadelphia Ave,Gilbertsville,Montgomery,Pennsylvania,19525,-75.618401,40.321602
8801,1012380,Zion Canyon Farmers Market,1212 Zion Park Blvd.,Springdale,Washington,Utah,84767,-113.004940,37.181499
8802,1004686,Zionsville Farmers Market,Hawthorne & Main Street,Zionsville,Boone,Indiana,46077,-86.261200,39.949100
8803,1011418,Zona Rosa Farmers' Market,Off of I-29 and Barry Road,Kansas City,Platte,Missouri,64153,-94.580864,39.246319

In [28]:
#remove any null values
clean_svicounty_df=svicounty_df.dropna()
clean_svicounty_df

,STATE,COUNTY,E_TOTPOP,E_POV150,M_POV150,E_UNEMP,M_UNEMP,E_HBURD,M_HBURD,E_NOHSDP,M_NOHSDP,E_UNINSUR,M_UNINSUR,E_MINRTY,M_MINRTY,EP_MINRTY,MP_MINRTY,EPL_MINRTY
0,Alabama,Autauga,55639,12611,1349,736,185,5029,576,4273,562,4345,725,14479,578,26.0,1.0,0.6337
1,Alabama,Baldwin,218289,36413,2802,4027,714,19350,1526,14823,1344,20501,1932,37334,1866,17.1,0.9,0.5022
2,Alabama,Barbour,25026,8965,673,649,182,2305,298,4497,387,2362,311,13694,271,54.7,1.1,0.8962
3,Alabama,Bibb,22374,5730,907,667,260,1580,319,3056,414,1878,387,5724,156,25.6,0.7,0.6292
4,Alabama,Blount,57755,13624,1151,1253,301,4060,431,6838,499,5746,695,7690,344,13.3,0.6,0.4147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3138,Wyoming,Sweetwater,43352,7713,1048,1437,348,2718,406,2098,396,5079,712,9205,604,21.2,1.4,0.5672
3139,Wyoming,Teton,23356,2779,765,280,173,2057,415,945,399,2666,692,4387,324,18.8,1.4,0.5331
3140,Wyoming,Uinta,20374,3673,688,453,200,995,240,903,191,2273,518,2581,145,12.7,0.7,0.4007
3141,Wyoming,Washakie,7933,1484,348,170,76,577,156,441,134,950,243,1446,64,18.2,0.8,0.5210
3142,Wyoming,Weston,6942,1316,356,118,77,522,147,329,116,781,257,649,246,9.3,3.5,0.3001

In [30]:
clean_svicounty_df['county_lower']=clean_svicounty_df['COUNTY'].str.lower()
clean_farm_market['county_lower']=clean_farm_market['County'].str.lower()

C:\Users\parkm\AppData\Local\Temp\ipykernel_64540\3154024816.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_farm_market['county_lower']=clean_farm_market['County'].str.lower()

In [32]:
#created clean_svicounty_dff and created merge
clean_svicounty_dff = pd.merge(clean_svicounty_df, clean_farm_market, how="outer", left_on=['county_lower','STATE'], right_on=['county_lower','State'])
clean_svicounty_dff.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8671 entries, 0 to 8670
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   STATE         8585 non-null   object
 1   COUNTY        8585 non-null   object
 2   E_TOTPOP      8585 non-null   float64
 3   E_POV150      8585 non-null   float64
 4   M_POV150      8585 non-null   float64
 5   E_UNEMP       8585 non-null   float64
 6   M_UNEMP       8585 non-null   float64
 7   E_HBURD       8585 non-null   float64
 8   M_HBURD       8585 non-null   float64
 9   E_NOHSDP      8585 non-null   float64
 10  M_NOHSDP      8585 non-null   float64
 11  E_UNINSUR     8585 non-null   float64
 12  M_UNINSUR     8585 non-null   float64
 13  E_MINRTY      8585 non-null   float64
 14  M_MINRTY      8585 non-null   float64
 15  EP_MINRTY     8585 non-null   float64
 16  MP_MINRTY     8585 non-null   float64
 17  EPL_MINRTY    8585 non-null   float64
 18  county_lower  8671 non-null   object
 19  FMID          7679 non-null   float64
 20  MarketName    7679 non-null   object
 21  street        7679 non-null   object
 22  city          7679 non-null   object
 23  County        7679 non-null   object
 24  State         7679 non-null   object
 25  zip           7679 non-null   object
 26  x             7679 non-null   float64
 27  y             7679 non-null   float64
dtypes: float64(19), object(9)
memory usage: 1.9+ MB

In [12]:

final_svicounty_dff = clean_svicounty_dff.drop(columns=['STATE','COUNTY','county_lower'])

In [13]:
final_svicounty_dff.to_csv('resources/farmers_market_svi.csv',index=False)

In [14]:
final_svicounty_dff=final_svicount_dff.astype({'E_TOTPOP':int,
                                               'E_POV150':int,
                                               'M_POV150':int,
                                               'E_UNEMP':int,
                                               'M_UNEMP':int,
                                               'E_HBURD':int,
                                               'M_HBURD':int,
                                               'E_NOHSDP':int,
                                               'M_NOHSDP':int,
                                               'E_UNINSUR':int,
                                               'M_UNINSUR':int,
                                               'E_MINRTY':int,
                                               'M_MINRTY':int,
                                               'EP_MINRTY':int,
                                               'MP_MINRTY':int})

NameError: name 'final_svicount_dff' is not defined